export async function code(n) {
  for (
    var varMakeOtp_1 = [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
      ],
      varMakeOtp_2 = n,
      varMakeOtp_3 = new Array(),
      varMakeOtp_4 = 0;
    varMakeOtp_4 <= varMakeOtp_2 - 1;
    varMakeOtp_4++
  ) {
    varMakeOtp_3[varMakeOtp_4] =
      varMakeOtp_1[parseInt(Math.random() * varMakeOtp_1.length)];
    varMakeOtp_3 = varMakeOtp_3;
    varMakeOtp_5 = varMakeOtp_3.join("");
  }
  return varMakeOtp_5;
}
